apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pandaacademy/backend:RC-2.b49f31f
        ports:
        - containerPort: 5001
      imagePullSecrets:
      - name: regcred